version: '2.1'

services:
  university-app:
    build:
      context: .
    image: university-app:1.0
    ports:
      - "8888:8888"
    container_name: universityapp
    expose:
      - "8888"
    depends_on:
      mysql-db:
        condition: service_healthy
  mysql-db:
    image: mysql:latest
    ports:
      - "3307:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: mysqldb
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: university_db

