platform: linux

image_resource:
  type: docker-image
  source:
    repository: zenika/alpine-maven
    tag: 3-jdk8

inputs:
  - name: university-resource

outputs:
  - name: artificaft-for-image

run:
  path: university-resource/ci/scripts/build.sh
