platform: linux

image_resource:
  type: docker-image
  source:
    repository: zenika/alpine-maven
    tag: 3-jdk8

inputs:
  - name: university-resource

outputs:
  - name: artefact-deploy

run:
  path: university-resource/ci/scripts/deploy-to-prod.sh