platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu

inputs:
  - name: university-resource
#  - name: built-university-resource

run:
  path: university-resource/ci/scripts/publish-image.sh

