platform: linux

image_resource:
  type: docker-image
    source:
      repository: openjdk
      tag: 8-jre-alpine

inputs:
  - name: university-resource


run:
  path: sh
  args:
    - -c
      - |
      cd university-resource
      ls -la

#run:
#  path: university-resource/ci/scripts/run-tests.sh