platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk:8-jre-alpine }

inputs:
  - name: university-resource


run:
  path: /bin/bash
  args:
    - -c
      - |
      cd university-resource
      ls -la

#run:
#  path: university-resource/ci/scripts/run-tests.sh