platform: linux

image_resource:
  type: docker-image
  source:
    repository: amidos/dcind
    tag: 2.0

inputs:
  - name: university-resource

run:
  path: university-resource/ci/scripts/run-tests.sh