platform: linux

image_resource:
  type: docker-image
  source:
    repository: dockerdozens/maven-dind-alpine
    tag: latest

inputs:
  - name: university-resource

run:
  path: university-resource/ci/scripts/run-tests.sh