platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jre-alpine

inputs:
  - name: university-resource

run:
  path: university-resource/ci/scripts/run-tests.sh