platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8-alpine}

inputs:
  - name: university-resource

run:
  path: university-resource/ci-hello/scripts/run-tests.sh