platform: linux

image_resource:
  type: docker-image
  source:
    repository: amidos/dcind
    tag: 2.0

inputs:
  - name: university-resource

run:
  path: bash
  args:
    - -exc
    - |
      source /docker-lib.sh
      start_docker

      docker run hello-world