platform: linux

image_resource:
  type: docker-image
  source: {repository: openjdk}

inputs:
  - name: university-resource


run:
  path: /bin/sh
  args:
    - -c
      - |
      cd university-resource
      ls -la

#run:
#  path: university-resource/ci/scripts/run-tests.sh