resources:
  - name: university-resource
    type: git
    source:
      uri: https://github.com/github-patrick/university-students.git
      branch: master

jobs:
  - name: job-hello-world
    public: true
    plan:
      - get: university-resource
        trigger: true
      - task: list-files
        file: university-resource/ci/tasks/hello-world.yml
      - task: run-tests
        file: university-resource/ci/tasks/run-tests.yml

  - name: second-job
    public: true
    plan:
      - get: university-resource
        trigger: true
      - task: run-tests
        file: university-resource/ci/tasks/run-tests.yml