resources:
  - name: university-resource
    type: git
    source:
      uri: https://github.com/github-patrick/university-students.git
      branch: master

jobs:
  - name: build
    public: true
    plan:
      - get: university-resource
        trigger: true
      - task: list-files
        file: university-resource/ci/tasks/build.yml
      - task: run-tests
        file: university-resource/ci/tasks/run-tests.yml

  - name: second-job
    public: true
    plan:
      - get: university-resource
        trigger: true
        passed: [job-hello-world]
      - task: run-tests
        file: university-resource/ci/tasks/run-tests.yml