resources:
  - name: university-resource
    type: git
    source:
      uri: https://github.com/github-patrick/university-students.git
      branch: master
  - name: university-image
    type: docker-image
    source:
      repository: ((docker-hub-username))/university-app
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))

jobs:
  - name: build
    public: true
    plan:
      - get: university-resource
        trigger: true
      - task: build-project
        file: university-resource/ci/tasks/build.yml

  - name: publish
    public: true
    plan:
      - get: university-resource
        trigger: true
        passed: [build]
      - task: publish-image
        file: university-resource/ci/tasks/publish.yml

      - put: university-image
        params:
          build: built-university-resource

  - name: e2e-tests
    public: true
    plan:
      - get: university-resource
        trigger: true
        passed: [publish]
      - task: run-tests
        privileged: true
        file: university-resource/ci/tasks/run-tests.yml

#        config:
#          platform: linux
#          image_resource:
#            type: docker-image
#            source:
#              repository: amidos/dcind
#              tag: 2.0
#          run:
#            path: bash
#            args:
#              - -exc
#              - |
#                source /docker-lib.sh
#                start_docker
#
#                docker pull busybox



