resources:
  - name: university-resource
    type: git
    source:
      uri: https://github.com/github-patrick/university-students.git
      branch: master

jobs:
  - name: build
    public: true
    plan:
      - get: university-resource
        trigger: true
      - task: build-project
        file: university-resource/ci/tasks/build.yml

  - name: e2e-tests
    public: true
    plan:
      - get: university-resource
        trigger: true
        passed: [build]
      - task: run-tests
        file: university-resource/ci/tasks/run-tests.yml